modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (26 is current forge version)
issueTrackerURL="http://my.issue.tracker/" #optional
[[mods]] #mandatory
modId="malum" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Malum" #mandatory
updateJSONURL="http://myurl.me/" #optional
displayURL="http://example.com/" #optional
logoFile="malum.png" #optional
credits="The Modding Community" #optional
authors="KittyKitCatCat and Queso" #optional
description='''
Test
'''
[[dependencies.malum]]
    modId="curios"
    mandatory=true
    versionRange="[FORGE-1.15.1-2.0-beta,)"
    ordering="AFTER"
    side="BOTH"